### ISSUE TITLE
User can set their Active Checklist

### ISSUE THREAD

**Issue by maximusmith529** [maximusmith529/Progress#13]
- [ ] Set Active Checklist function 
(Should make all other checklists to inactive and the current to active via the database)
- [ ] Implement function on isActive switches in the Checklists Fragment
- [ ] Implement function after a new checklist is made in the CreateChecklist Activity
